export const medicalGlossary: Record<string, string> = {
  // Acronyms
  "ECG": "Electrocardiogram, a test that records the electrical activity of the heart.",
  "EKG": "Electrocardiogram, a test that records the electrical activity of the heart.",
  "MI": "Myocardial Infarction, commonly known as a heart attack.",
  "BP": "Blood Pressure.",
  "HR": "Heart Rate.",
  "RR": "Respiratory Rate.",
  "SpO2": "Oxygen saturation, a measure of the amount of oxygen-carrying hemoglobin in the blood.",
  "COPD": "Chronic Obstructive Pulmonary Disease, a group of lung diseases that block airflow and make it difficult to breathe.",
  "MRI": "Magnetic Resonance Imaging.",
  "CT": "Computed Tomography.",
  "CBC": "Complete Blood Count.",
  "BMP": "Basic Metabolic Panel.",
  "CMP": "Comprehensive Metabolic Panel.",
  "UTI": "Urinary Tract Infection.",
  "URI": "Upper Respiratory Infection.",
  "CXR": "Chest X-Ray.",
  "NPO": "Nothing by mouth (nil per os).",
  "PRN": "As needed (pro re nata).",
  "QD": "Once a day.",
  "BID": "Twice a day.",
  "TID": "Three times a day.",
  "QID": "Four times a day.",
  "Q4H": "Every 4 hours.",
  "CHF": "Congestive Heart Failure.",
  "AFib": "Atrial Fibrillation, an irregular and often very rapid heart rhythm.",
  "STEMI": "ST-Elevation Myocardial Infarction, a severe type of heart attack.",
  "NSTEMI": "Non-ST-Elevation Myocardial Infarction.",
  "CVA": "Cerebrovascular Accident, commonly known as a stroke.",
  "TIA": "Transient Ischemic Attack, often called a mini-stroke.",
  "DVT": "Deep Vein Thrombosis, a blood clot in a deep vein, usually in the legs.",
  "PE": "Pulmonary Embolism, a blockage in one of the pulmonary arteries in your lungs.",
  "GCS": "Glasgow Coma Scale, used to objectively describe the extent of impaired consciousness.",
  "BUN": "Blood Urea Nitrogen, a medical test that measures the amount of urea nitrogen found in blood.",
  
  // Terms
  "hypertension": "High blood pressure.",
  "hypotension": "Low blood pressure.",
  "tachycardia": "A heart rate that's too fast.",
  "bradycardia": "A heart rate that's too slow.",
  "tachypnea": "Abnormally rapid breathing.",
  "dyspnea": "Shortness of breath or difficulty breathing.",
  "apnea": "Temporary cessation of breathing.",
  "cyanosis": "A bluish discoloration of the skin resulting from poor circulation or inadequate oxygenation of the blood.",
  "diaphoresis": "Sweating, especially to an unusual degree as a symptom of disease or a side effect of a drug.",
  "edema": "Swelling caused by excess fluid trapped in your body's tissues.",
  "erythema": "Superficial reddening of the skin, usually in patches, as a result of injury or irritation causing dilatation of the blood capillaries.",
  "ischemia": "An inadequate blood supply to an organ or part of the body, especially the heart muscles.",
  "infarction": "Tissue death (necrosis) due to inadequate blood supply to the affected area.",
  "necrosis": "The death of most or all of the cells in an organ or tissue due to disease, injury, or failure of the blood supply.",
  "sepsis": "A life-threatening condition that arises when the body's response to infection causes injury to its own tissues and organs.",
  "anaphylaxis": "An acute allergic reaction to an antigen to which the body has become hypersensitive.",
  "syncope": "Temporary loss of consciousness caused by a fall in blood pressure.",
  "vertigo": "A sensation of whirling and loss of balance.",
  "hematemesis": "The vomiting of blood.",
  "hemoptysis": "The coughing up of blood.",
  "melena": "Dark sticky feces containing partly digested blood.",
  "hematochezia": "The passage of fresh blood through the anus, usually in or with stools.",
  "polyuria": "Production of abnormally large volumes of dilute urine.",
  "polydipsia": "Abnormally great thirst as a symptom of disease (such as diabetes) or psychological disturbance.",
  "polyphagia": "Excessive or extreme hunger.",
  "pruritus": "Severe itching of the skin.",
  "alopecia": "The partial or complete absence of hair from areas of the body where it normally grows; baldness.",
  "jaundice": "A medical condition with yellowing of the skin or whites of the eyes, arising from excess of the pigment bilirubin.",
  "hepatomegaly": "Abnormal enlargement of the liver.",
  "splenomegaly": "Abnormal enlargement of the spleen.",
  "ascites": "The accumulation of fluid in the peritoneal cavity, causing abdominal swelling.",
  "pleural effusion": "A buildup of fluid between the tissues that line the lungs and the chest.",
  "pneumothorax": "The presence of air or gas in the cavity between the lungs and the chest wall, causing collapse of the lung.",
  "atelectasis": "Partial or complete collapse of the lung.",
  "arrhythmia": "A condition in which the heart beats with an irregular or abnormal rhythm.",
  "murmur": "An unusual, 'whooshing' heart sound that may be innocent or may reflect disease or malformation.",
  "bruit": "A sound, typically an abnormal one, heard through a stethoscope; a murmur.",
  "crepitus": "A grating sound or sensation produced by friction between bone and cartilage or the fractured parts of a bone.",
  "stridor": "A harsh or grating sound heard during breathing, caused by obstruction of the windpipe or larynx.",
  "wheeze": "Breathe with a whistling or rattling sound in the chest, as a result of obstruction in the air passages.",
  "rhonchi": "Continuous low pitched, rattling lung sounds that often resemble snoring.",
  "rales": "Abnormal crackling sound made during breathing.",
  "crackles": "Abnormal crackling sound made during breathing.",
  "myalgia": "Pain in a muscle or group of muscles.",
  "arthralgia": "Pain in a joint.",
  "neuropathy": "Disease or dysfunction of one or more peripheral nerves, typically causing numbness or weakness.",
  "paresthesia": "An abnormal sensation, typically tingling or pricking ('pins and needles').",
  "aphasia": "Loss of ability to understand or express speech, caused by brain damage.",
  "dysphagia": "Difficulty or discomfort in swallowing, as a symptom of disease.",
  "dysarthria": "Difficult or unclear articulation of speech that is otherwise linguistically normal.",
  "ataxia": "The loss of full control of bodily movements.",
  "nystagmus": "Rapid involuntary movements of the eyes.",
  "photophobia": "Extreme sensitivity to light.",
  "phonophobia": "Extreme sensitivity to noise.",
  "tinnitus": "Ringing or buzzing in the ears.",
  "epistaxis": "Bleeding from the nose.",
  "rhinorrhea": "A condition where the nasal cavity is filled with a significant amount of mucus fluid (runny nose).",
  "otorrhea": "A discharge from the ear.",
  "exudate": "A mass of cells and fluid that has seeped out of blood vessels or an organ, especially in inflammation.",
  "transudate": "A fluid that passes through a membrane, which filters out all the cells and much of the protein, yielding a watery solution.",
  "purulent": "Consisting of, containing, or discharging pus.",
  "erythematous": "Redness of the skin or mucous membranes.",
  "macule": "A flat, distinct, discolored area of skin less than 1 centimeter wide.",
  "papule": "A small, raised, solid pimple or swelling, often forming part of a rash on the skin and typically inflamed but not producing pus.",
  "vesicle": "A small fluid-filled blister on the skin.",
  "bulla": "A large blister containing watery fluid.",
  "pustule": "A small blister or pimple on the skin containing pus.",
  "nodule": "A small swelling or aggregation of cells in the body.",
  "plaque": "A small, abnormal patch of tissue on a body part or an organ.",
  "ulcer": "An open sore on an external or internal surface of the body, caused by a break in the skin or mucous membrane that fails to heal.",
  "fissure": "A long, narrow opening or line of breakage made by cracking or splitting, especially in skin or rock.",
  "excoriation": "A scratch mark; a linear break in the skin surface, usually covered with blood or serous crusts.",
  "lichenification": "Thickening of the skin with accentuation of normal skin markings; it is a result of chronic scratching or rubbing.",
  "hyperkeratosis": "Abnormal thickening of the outer layer of the skin.",
  "parakeratosis": "A mode of keratinization characterized by the retention of nuclei in the stratum corneum.",
  "acanthosis": "Diffuse epidermal hyperplasia (thickening of the skin).",
  "spongiosis": "Intercellular edema (abnormal accumulation of fluid) in the epidermis.",
  "apoptosis": "The death of cells which occurs as a normal and controlled part of an organism's growth or development.",
  "hyperplasia": "The enlargement of an organ or tissue caused by an increase in the reproduction rate of its cells.",
  "hypertrophy": "The enlargement of an organ or tissue from the increase in size of its cells.",
  "atrophy": "Waste away, typically due to the degeneration of cells, or become vestigial during evolution.",
  "metaplasia": "Abnormal change in the nature of a tissue.",
  "dysplasia": "The enlargement of an organ or tissue by the proliferation of cells of an abnormal type, as a developmental disorder or an early stage in the development of cancer.",
  "neoplasia": "The formation or presence of a new, abnormal growth of tissue.",
  "malignant": "Very virulent or infectious; (of a tumor) tending to invade normal tissue or to recur after removal; cancerous.",
  "benign": "Not harmful in effect: in particular, (of a tumor) not malignant.",
  "idiopathic": "Relating to or denoting any disease or condition which arises spontaneously or for which the cause is unknown.",
  "iatrogenic": "Relating to illness caused by medical examination or treatment.",
  "nosocomial": "(Of a disease) originating in a hospital.",
  "congenital": "(Of a disease or physical abnormality) present from birth.",
  "hereditary": "Conferred by or based on inheritance.",
  "familial": "Relating to or occurring in a family or its members.",
  "sporadic": "Occurring at irregular intervals or only in a few places; scattered or isolated.",
  "endemic": "(Of a disease or condition) regularly found among particular people or in a certain area.",
  "epidemic": "A widespread occurrence of an infectious disease in a community at a particular time.",
  "pandemic": "(Of a disease) prevalent over a whole country or the world.",
  "zoonotic": "Relating to a disease that can be transmitted from animals to people.",
  "vector-borne": "Infections transmitted by the bite of infected arthropod species, such as mosquitoes, ticks, triatomine bugs, sandflies, and blackflies.",
  "asymptomatic": "(Of a condition or a person) producing or showing no symptoms.",
  "prodrome": "An early symptom indicating the onset of a disease or illness.",
  "syndrome": "A group of symptoms which consistently occur together, or a condition characterized by a set of associated symptoms.",
  "prognosis": "The likely course of a disease or ailment.",
  "diagnosis": "The identification of the nature of an illness or other problem by examination of the symptoms.",
  "differential diagnosis": "The process of differentiating between two or more conditions which share similar signs or symptoms.",
  "etiology": "The cause, set of causes, or manner of causation of a disease or condition.",
  "pathogenesis": "The manner of development of a disease.",
  "pathophysiology": "The disordered physiological processes associated with disease or injury.",
  "histology": "The study of the microscopic structure of tissues.",
  "cytology": "The branch of biology concerned with the structure and function of plant and animal cells.",
  "morphology": "The branch of biology that deals with the form of living organisms, and with relationships between their structures.",
  "anatomy": "The branch of science concerned with the bodily structure of humans, animals, and other living organisms, especially as revealed by dissection and the separation of parts.",
  "physiology": "The branch of biology that deals with the normal functions of living organisms and their parts.",
  "pharmacology": "The branch of medicine concerned with the uses, effects, and modes of action of drugs.",
  "toxicology": "The branch of science concerned with the nature, effects, and detection of poisons.",
  "epidemiology": "The branch of medicine which deals with the incidence, distribution, and possible control of diseases and other factors relating to health.",
  "immunology": "The branch of medicine and biology concerned with immunity.",
  "genetics": "The study of heredity and the variation of inherited characteristics.",
  "oncology": "The study and treatment of tumors.",
  "cardiology": "The branch of medicine that deals with diseases and abnormalities of the heart.",
  "pulmonology": "The branch of medicine concerned with the anatomy, physiology, and pathology of the lungs.",
  "gastroenterology": "The branch of medicine which deals with disorders of the stomach and intestines.",
  "hepatology": "The branch of medicine that incorporates the study of liver, gallbladder, biliary tree, and pancreas as well as management of their disorders.",
  "nephrology": "The branch of medicine that deals with the physiology and diseases of the kidneys.",
  "urology": "The branch of medicine and physiology concerned with the function and disorders of the urinary system.",
  "endocrinology": "The branch of physiology and medicine concerned with endocrine glands and hormones.",
  "neurology": "The branch of medicine or biology that deals with the anatomy, functions, and organic disorders of nerves and the nervous system.",
  "psychiatry": "The study and treatment of mental illness, emotional disturbance, and abnormal behavior.",
  "psychology": "The scientific study of the human mind and its functions, especially those affecting behavior in a given context.",
  "dermatology": "The branch of medicine concerned with the diagnosis and treatment of skin disorders.",
  "rheumatology": "The study of rheumatism, arthritis, and other disorders of the joints, muscles, and ligaments.",
  "orthopedics": "The branch of medicine dealing with the correction of deformities of bones or muscles.",
  "hematology": "The branch of medicine involving study and treatment of the blood.",
  "infectious disease": "Disorders caused by organisms — such as bacteria, viruses, fungi or parasites.",
  "pediatrics": "The branch of medicine dealing with children and their diseases.",
  "geriatrics": "The branch of medicine or social science dealing with the health and care of old people.",
  "obstetrics": "The branch of medicine and surgery concerned with childbirth and the care of women giving birth.",
  "gynecology": "The branch of physiology and medicine which deals with the functions and diseases specific to women and girls, especially those affecting the reproductive system.",
  "surgery": "The medical specialty that uses operative manual and instrumental techniques on a person to investigate or treat a pathological condition such as a disease or injury.",
  "anesthesiology": "The branch of medicine concerned with anesthesia and anesthetics.",
  "radiology": "The science dealing with X-rays and other high-energy radiation, especially the use of such radiation for the diagnosis and treatment of disease.",
  "pathology": "The science of the causes and effects of diseases, especially the branch of medicine that deals with the laboratory examination of samples of body tissue for diagnostic or forensic purposes.",
  "otolaryngology": "The study of diseases of the ear and throat.",
  "ophthalmology": "The branch of medicine and surgery which deals with the diagnosis and treatment of eye disorders."
};

// Create a list of term objects, sorted by length (descending) to match longest phrases first
export const sortedGlossaryTerms = Object.keys(medicalGlossary)
  .sort((a, b) => b.length - a.length)
  .map(term => ({
    term,
    lowerTerm: term.toLowerCase(),
    definition: medicalGlossary[term]
  }));
